// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("CountryId", Name = "IX_Addresses_CountryId")]
[Index("UserId", Name = "IX_Addresses_UserId")]
public partial class Address
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public int CountryId { get; set; }

    [Required]
    [StringLength(50)]
    public string StreetNumber { get; set; }

    [Required]
    [StringLength(200)]
    public string AddressLine1 { get; set; }

    [StringLength(200)]
    public string AddressLine2 { get; set; }

    [Required]
    [StringLength(100)]
    public string City { get; set; }

    [Required]
    [StringLength(100)]
    public string Ward { get; set; }

    [Required]
    [StringLength(20)]
    public string Postcode { get; set; }

    [Required]
    [StringLength(100)]
    public string Province { get; set; }

    public bool IsDefault { get; set; }

    [StringLength(200)]
    public string CustomerName { get; set; }

    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [StringLength(100)]
    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("Addresses")]
    public virtual Country Country { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Addresses")]
    public virtual User User { get; set; }
}