// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("UserId", Name = "IX_Blogs_UserId")]
public partial class Blog
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(200)]
    public string Title { get; set; }

    [Required]
    public string Description { get; set; }

    [Required]
    [StringLength(500)]
    public string Thumbnail { get; set; }

    public Guid UserId { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [StringLength(100)]
    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Blog")]
    public virtual ICollection<BlogSection> BlogSections { get; set; } = new List<BlogSection>();

    [ForeignKey("UserId")]
    [InverseProperty("Blogs")]
    public virtual User User { get; set; }
}