// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("BlogId", Name = "IX_BlogSections_BlogId")]
public partial class BlogSection
{
    [Key]
    public Guid Id { get; set; }

    public Guid BlogId { get; set; }

    [Required]
    [StringLength(50)]
    public string ContentType { get; set; }

    [Required]
    [StringLength(200)]
    public string Subtitle { get; set; }

    [Required]
    public string Content { get; set; }

    public int Order { get; set; }

    [ForeignKey("BlogId")]
    [InverseProperty("BlogSections")]
    public virtual Blog Blog { get; set; }
}