// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("SessionId", Name = "IX_ChatHistories_SessionId")]
[Index("UserId", Name = "IX_ChatHistories_UserId")]
public partial class ChatHistory
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    [Required]
    public string MessageContent { get; set; }

    [Required]
    [StringLength(10)]
    public string SenderType { get; set; }

    public DateTimeOffset Timestamp { get; set; }

    [Required]
    [StringLength(100)]
    public string SessionId { get; set; }

    [Required]
    [StringLength(100)]
    public string CreatedBy { get; set; }

    [Required]
    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [StringLength(100)]
    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ChatHistories")]
    public virtual User User { get; set; }
}