// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ReviewId", Name = "IX_Replies_ReviewId", IsUnique = true)]
[Index("UserId", Name = "IX_Replies_UserId")]
public partial class Reply
{
    [Key]
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public Guid ReviewId { get; set; }

    [Required]
    [StringLength(1000)]
    public string ReplyContent { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ReviewId")]
    [InverseProperty("Reply")]
    public virtual Review Review { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Replies")]
    public virtual User User { get; set; }
}