// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductItemId", Name = "IX_Reviews_ProductItemId")]
[Index("UserId", Name = "IX_Reviews_UserId")]
public partial class Review
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid ProductItemId { get; set; }

    public float RatingValue { get; set; }

    [Required]
    [StringLength(2000)]
    public string Comment { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Review")]
    public virtual Reply Reply { get; set; }

    [InverseProperty("Review")]
    public virtual ICollection<ReviewImage> ReviewImages { get; set; } = new List<ReviewImage>();

    [ForeignKey("UserId")]
    [InverseProperty("Reviews")]
    public virtual User User { get; set; }
}