// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ReviewId", Name = "IX_ReviewImages_ReviewId")]
public partial class ReviewImage
{
    [Key]
    public Guid Id { get; set; }

    public Guid ReviewId { get; set; }

    [Required]
    [StringLength(1000)]
    public string ImageUrl { get; set; }

    [ForeignKey("ReviewId")]
    [InverseProperty("ReviewImages")]
    public virtual Review Review { get; set; }
}