// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("UserId", Name = "IX_Transactions_UserId")]
public partial class Transaction
{
    [Key]
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    [Required]
    public string TransactionType { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Required]
    public string Status { get; set; }

    [Required]
    public string QrImageUrl { get; set; }

    [Required]
    public string BankInformation { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [Required]
    public string CreatedBy { get; set; }

    [Required]
    public string LastUpdatedBy { get; set; }

    public string ApprovedBy { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public DateTimeOffset LastUpdatedTime { get; set; }

    public DateTimeOffset? ApprovedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Transactions")]
    public virtual User User { get; set; }
}