// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("EmailAddress", Name = "IX_Users_EmailAddress")]
[Index("RoleId", Name = "IX_Users_RoleId")]
[Index("SkinConditionId", Name = "IX_Users_SkinConditionId")]
[Index("SkinTypeId", Name = "IX_Users_SkinTypeId")]
public partial class User
{
    [Key]
    public Guid UserId { get; set; }

    public Guid? SkinTypeId { get; set; }

    public Guid? RoleId { get; set; }

    [Required]
    public string UserName { get; set; }

    [Required]
    [StringLength(100)]
    public string SurName { get; set; }

    [Required]
    [StringLength(100)]
    public string LastName { get; set; }

    [Required]
    [StringLength(100)]
    public string EmailAddress { get; set; }

    [Required]
    [StringLength(20)]
    public string PhoneNumber { get; set; }

    [Required]
    public string Status { get; set; }

    [Required]
    [StringLength(500)]
    public string Password { get; set; }

    [StringLength(500)]
    public string AvatarUrl { get; set; }

    [Required]
    [StringLength(100)]
    public string CreatedBy { get; set; }

    [Required]
    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    [StringLength(100)]
    public string DeletedBy { get; set; }

    public DateTimeOffset CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    public int? Age { get; set; }

    [Column(TypeName = "date")]
    public DateTime? DoB { get; set; }

    [StringLength(1000)]
    public string Diet { get; set; }

    [StringLength(1000)]
    public string DailyRoutine { get; set; }

    [StringLength(1000)]
    public string Allergy { get; set; }

    [StringLength(1000)]
    public string Certificate { get; set; }

    public Guid? SkinConditionId { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    [InverseProperty("User")]
    public virtual ICollection<Blog> Blogs { get; set; } = new List<Blog>();

    [InverseProperty("User")]
    public virtual ICollection<ChatHistory> ChatHistories { get; set; } = new List<ChatHistory>();

    [InverseProperty("User")]
    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    [InverseProperty("User")]
    public virtual ICollection<Reply> Replies { get; set; } = new List<Reply>();

    [InverseProperty("User")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [ForeignKey("RoleId")]
    [InverseProperty("Users")]
    public virtual Role Role { get; set; }

    [ForeignKey("SkinConditionId")]
    [InverseProperty("Users")]
    public virtual SkinCondition SkinCondition { get; set; }

    [ForeignKey("SkinTypeId")]
    [InverseProperty("Users")]
    public virtual SkinType SkinType { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}