// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class CancelReason
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal RefundRate { get; set; }

    [InverseProperty("CancelReason")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}