// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("AddressId", Name = "IX_Orders_AddressId")]
[Index("CancelReasonId", Name = "IX_Orders_CancelReasonId")]
[Index("PaymentMethodId", Name = "IX_Orders_PaymentMethodId")]
[Index("UserId", Name = "IX_Orders_UserId")]
[Index("VoucherId", Name = "IX_Orders_VoucherId")]
public partial class Order
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string Status { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal OrderTotal { get; set; }

    public Guid? CancelReasonId { get; set; }

    public Guid UserId { get; set; }

    public Guid PaymentMethodId { get; set; }

    public Guid AddressId { get; set; }

    public Guid? VoucherId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("CancelReasonId")]
    [InverseProperty("Orders")]
    public virtual CancelReason CancelReason { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("PaymentMethodId")]
    [InverseProperty("Orders")]
    public virtual PaymentMethod PaymentMethod { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<StatusChange> StatusChanges { get; set; } = new List<StatusChange>();

    [ForeignKey("VoucherId")]
    [InverseProperty("Orders")]
    public virtual Voucher Voucher { get; set; }
}