// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class PaymentMethod
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string PaymentType { get; set; }

    [Required]
    [StringLength(200)]
    public string ImageUrl { get; set; }

    [InverseProperty("PaymentMethod")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}