// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class ProductStatus
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(100)]
    public string StatusName { get; set; }

    [Required]
    [StringLength(500)]
    public string Description { get; set; }

    [InverseProperty("ProductStatus")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}