// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_ProductForSkinConditions_ProductId")]
[Index("SkinConditionId", Name = "IX_ProductForSkinConditions_SkinConditionId")]
[Index("ProductId", "SkinConditionId", Name = "UQ_ProductForSkinConditions_Product_SkinCondition", IsUnique = true)]
public partial class ProductForSkinCondition
{
    [Key]
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public Guid SkinConditionId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductForSkinConditions")]
    public virtual Product Product { get; set; }

    [ForeignKey("SkinConditionId")]
    [InverseProperty("ProductForSkinConditions")]
    public virtual SkinCondition SkinCondition { get; set; }
}