// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ParentCategoryId", Name = "IX_ProductCategories_ParentCategoryId")]
public partial class ProductCategory
{
    [Key]
    public Guid Id { get; set; }

    public Guid? ParentCategoryId { get; set; }

    [Required]
    [StringLength(100)]
    public string CategoryName { get; set; }

    [InverseProperty("ParentCategory")]
    public virtual ICollection<ProductCategory> InverseParentCategory { get; set; } = new List<ProductCategory>();

    [ForeignKey("ParentCategoryId")]
    [InverseProperty("InverseParentCategory")]
    public virtual ProductCategory ParentCategory { get; set; }

    [InverseProperty("ProductCategory")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("ProductCategory")]
    public virtual ICollection<Variation> Variations { get; set; } = new List<Variation>();
}