// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_ProductImages_ProductId")]
public partial class ProductImage
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(500)]
    public string ImageUrl { get; set; }

    public bool IsThumbnail { get; set; }

    public Guid ProductId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductImages")]
    public virtual Product Product { get; set; }
}