// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_ProductForSkinTypes_ProductId")]
[Index("SkinTypeId", Name = "IX_ProductForSkinTypes_SkinTypeId")]
public partial class ProductForSkinType
{
    [Key]
    public Guid Id { get; set; }

    public Guid ProductId { get; set; }

    public Guid SkinTypeId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductForSkinTypes")]
    public virtual Product Product { get; set; }

    [ForeignKey("SkinTypeId")]
    [InverseProperty("ProductForSkinTypes")]
    public virtual SkinType SkinType { get; set; }
}