// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductId", Name = "IX_ProductConfigurations_ProductId")]
[Index("VariationOptionId", Name = "IX_ProductConfigurations_VariationOptionId")]
public partial class ProductConfiguration
{
    [Key]
    public Guid Id { get; set; }

    public Guid VariationOptionId { get; set; }

    public Guid? ProductId { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductConfigurations")]
    public virtual Product Product { get; set; }

    [ForeignKey("VariationOptionId")]
    [InverseProperty("ProductConfigurations")]
    public virtual VariationOption VariationOption { get; set; }
}