// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("BrandId", Name = "IX_Products_BrandId")]
[Index("ProductCategoryId", Name = "IX_Products_ProductCategoryId")]
[Index("ProductStatusId", Name = "IX_Products_ProductStatusId")]
public partial class Product
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(255)]
    public string EnglishName { get; set; }

    [Required]
    public string Description { get; set; }

    public int SoldCount { get; set; }

    public double Rating { get; set; }

    [StringLength(500)]
    public string StorageInstruction { get; set; }

    [StringLength(500)]
    public string UsageInstruction { get; set; }

    [StringLength(1000)]
    public string DetailedIngredients { get; set; }

    [StringLength(255)]
    public string MainFunction { get; set; }

    [StringLength(255)]
    public string Texture { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Price { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MarketPrice { get; set; }

    [StringLength(500)]
    public string KeyActiveIngredients { get; set; }

    [StringLength(50)]
    public string ExpiryDate { get; set; }

    [StringLength(255)]
    public string SkinIssues { get; set; }

    public Guid? ProductStatusId { get; set; }

    public Guid? BrandId { get; set; }

    public Guid? ProductCategoryId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    public int QuantityInStock { get; set; }

    [ForeignKey("BrandId")]
    [InverseProperty("Products")]
    public virtual Brand Brand { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    [InverseProperty("Product")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [ForeignKey("ProductCategoryId")]
    [InverseProperty("Products")]
    public virtual ProductCategory ProductCategory { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; } = new List<ProductConfiguration>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductForSkinCondition> ProductForSkinConditions { get; set; } = new List<ProductForSkinCondition>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductForSkinType> ProductForSkinTypes { get; set; } = new List<ProductForSkinType>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [ForeignKey("ProductStatusId")]
    [InverseProperty("Products")]
    public virtual ProductStatus ProductStatus { get; set; }
}