// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class SkinType
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(255)]
    public string Name { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    [InverseProperty("SkinType")]
    public virtual ICollection<ProductForSkinType> ProductForSkinTypes { get; set; } = new List<ProductForSkinType>();
}