// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("OrderId", Name = "IX_StatusChanges_OrderId")]
public partial class StatusChange
{
    [Key]
    public Guid Id { get; set; }

    public DateTimeOffset Date { get; set; }

    [Required]
    [StringLength(100)]
    public string Status { get; set; }

    public Guid OrderId { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("StatusChanges")]
    public virtual Order Order { get; set; }
}