// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ProductCategoryId", Name = "IX_Variations_ProductCategoryId")]
public partial class Variation
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Name { get; set; }

    public Guid? ProductCategoryId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ProductCategoryId")]
    [InverseProperty("Variations")]
    public virtual ProductCategory ProductCategory { get; set; }

    [InverseProperty("Variation")]
    public virtual ICollection<VariationOption> VariationOptions { get; set; } = new List<VariationOption>();
}