// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("VariationId", Name = "IX_VariationOptions_VariationId")]
public partial class VariationOption
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(255)]
    public string Value { get; set; }

    public Guid VariationId { get; set; }

    public string CreatedBy { get; set; }

    public string LastUpdatedBy { get; set; }

    public string DeletedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("VariationOption")]
    public virtual ICollection<ProductConfiguration> ProductConfigurations { get; set; } = new List<ProductConfiguration>();

    [ForeignKey("VariationId")]
    [InverseProperty("VariationOptions")]
    public virtual Variation Variation { get; set; }
}