// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("StaffId", Name = "IX_Appointments_StaffId")]
[Index("UserId", Name = "IX_Appointments_UserId")]
public partial class Appointment
{
    [Key]
    public Guid Id { get; set; }

    public Guid? UserId { get; set; }

    public Guid? StaffId { get; set; }

    [Column(TypeName = "date")]
    public DateTime AppointmentDate { get; set; }

    public DateTimeOffset StartDateTime { get; set; }

    public DateTimeOffset? EndDateTime { get; set; }

    public int? DurationMinutes { get; set; }

    public byte Status { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public Guid? ServiceId { get; set; }

    public Guid? ScheduleId { get; set; }

    public Guid? SessionId { get; set; }

    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Appointment")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [ForeignKey("ScheduleId")]
    [InverseProperty("Appointments")]
    public virtual WorkSchedule Schedule { get; set; }

    [ForeignKey("ServiceId")]
    [InverseProperty("Appointments")]
    public virtual Service Service { get; set; }

    [ForeignKey("SessionId")]
    [InverseProperty("Appointments")]
    public virtual TreatmentSession Session { get; set; }
}