// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

public partial class Holiday
{
    [Key]
    public Guid Id { get; set; }

    [Column(TypeName = "date")]
    public DateTime HolidayDate { get; set; }

    [StringLength(500)]
    public string Description { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public bool IsDeleted { get; set; }
}