// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("StaffId", Name = "IX_Registrations_StaffId")]
public partial class Registration
{
    [Key]
    public Guid Id { get; set; }

    public Guid? StaffId { get; set; }

    [Column(TypeName = "date")]
    public DateTime StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan StartTime { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan EndTime { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public Guid? TemplateId { get; set; }

    public Guid? SlotId { get; set; }

    public string Notes { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Registration")]
    public virtual ICollection<RegistrationWeekday> RegistrationWeekdays { get; set; } = new List<RegistrationWeekday>();

    [ForeignKey("SlotId")]
    [InverseProperty("Registrations")]
    public virtual Slot Slot { get; set; }

    [ForeignKey("TemplateId")]
    [InverseProperty("Registrations")]
    public virtual WorkTemplate Template { get; set; }

    [InverseProperty("Registration")]
    public virtual ICollection<WorkSchedule> WorkSchedules { get; set; } = new List<WorkSchedule>();
}