// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[PrimaryKey("Weekday", "RegistrationId")]
[Index("RegistrationId", Name = "IX_RegistrationWeekdays_RegistrationId")]
public partial class RegistrationWeekday
{
    [Key]
    public byte Weekday { get; set; }

    [Key]
    public Guid RegistrationId { get; set; }

    [ForeignKey("RegistrationId")]
    [InverseProperty("RegistrationWeekdays")]
    public virtual Registration Registration { get; set; }
}