// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ReportId", Name = "IX_ReportImages_ReportId")]
public partial class ReportImage
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    [StringLength(1000)]
    public string ImageUrl { get; set; }

    public Guid ReportId { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("ReportId")]
    [InverseProperty("ReportImages")]
    public virtual Report Report { get; set; }
}