// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("AppointmentId", Name = "IX_Reports_AppointmentId")]
public partial class Report
{
    [Key]
    public Guid Id { get; set; }

    public Guid? StaffId { get; set; }

    public Guid? CustomerId { get; set; }

    [Column(TypeName = "date")]
    public DateTime ReportDate { get; set; }

    public string Summary { get; set; }

    public string Diagnosis { get; set; }

    public string Observations { get; set; }

    public string Vitals { get; set; }

    public string Recommendation { get; set; }

    [Column(TypeName = "date")]
    public DateTime? NextFollowUpDate { get; set; }

    public string FollowUpInstructions { get; set; }

    public byte Status { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public Guid? AppointmentId { get; set; }

    public bool IsDeleted { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("Reports")]
    public virtual Appointment Appointment { get; set; }

    [InverseProperty("Report")]
    public virtual ICollection<ReportImage> ReportImages { get; set; } = new List<ReportImage>();
}