// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("RoomName", Name = "IX_Rooms_RoomName")]
public partial class Room
{
    [Key]
    public Guid Id { get; set; }

    [StringLength(200)]
    public string Location { get; set; }

    public int? FloorNumber { get; set; }

    [StringLength(200)]
    public string RoomName { get; set; }

    public int? Capacity { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    [StringLength(100)]
    public string LastUpdatedBy { get; set; }

    public DateTimeOffset? CreatedTime { get; set; }

    public DateTimeOffset? LastUpdatedTime { get; set; }

    public DateTimeOffset? DeletedTime { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Room")]
    public virtual ICollection<WorkSchedule> WorkSchedules { get; set; } = new List<WorkSchedule>();
}