// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("StaffId", Name = "IX_ScheduleOverrides_StaffId")]
public partial class ScheduleOverride
{
    [Key]
    public Guid Id { get; set; }

    public Guid StaffId { get; set; }

    [Column(TypeName = "date")]
    public DateTime OverrideDate { get; set; }

    public byte ActionType { get; set; }

    public string Note { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public bool IsDeleted { get; set; }
}