// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("CustomerId", Name = "IX_TreatmentPlans_CustomerId")]
public partial class TreatmentPlan
{
    [Key]
    public Guid Id { get; set; }

    public Guid? CreatedByStaffId { get; set; }

    public Guid? CustomerId { get; set; }

    public DateTimeOffset? CustomerApprovedAt { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal? EstimatedCost { get; set; }

    public int? DurationWeeks { get; set; }

    public int? TotalSessions { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public string Diagnosis { get; set; }

    public string Goal { get; set; }

    [Column(TypeName = "date")]
    public DateTime? StartDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime? EndDate { get; set; }

    public byte Status { get; set; }

    public string Description { get; set; }

    public DateTimeOffset? LastUpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Plan")]
    public virtual ICollection<TreatmentSession> TreatmentSessions { get; set; } = new List<TreatmentSession>();
}