// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("PlanId", Name = "IX_TreatmentSessions_PlanId")]
public partial class TreatmentSession
{
    [Key]
    public Guid Id { get; set; }

    public int? SessionNumber { get; set; }

    public Guid? StaffId { get; set; }

    [Column(TypeName = "date")]
    public DateTime SessionDate { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan? StartTime { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan? EndTime { get; set; }

    [StringLength(500)]
    public string TreatmentProcedure { get; set; }

    public string ResultSummary { get; set; }

    public byte Status { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public string Devices { get; set; }

    public string Kits { get; set; }

    public Guid PlanId { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Session")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("PlanId")]
    [InverseProperty("TreatmentSessions")]
    public virtual TreatmentPlan Plan { get; set; }
}