// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SPSS.BusinessObject.Models;

[Index("ShiftDate", Name = "IX_WorkSchedules_ShiftDate")]
[Index("StaffId", Name = "IX_WorkSchedules_StaffId")]
public partial class WorkSchedule
{
    [Key]
    public Guid Id { get; set; }

    public Guid StaffId { get; set; }

    [Column(TypeName = "date")]
    public DateTime ShiftDate { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan StartTime { get; set; }

    [Column(TypeName = "time(0)")]
    public TimeSpan EndTime { get; set; }

    public int? SlotIndex { get; set; }

    public byte Status { get; set; }

    public DateTimeOffset CreatedAt { get; set; }

    public DateTimeOffset? UpdatedAt { get; set; }

    public Guid? RegistrationId { get; set; }

    public Guid? RoomId { get; set; }

    public string Notes { get; set; }

    public bool IsDeleted { get; set; }

    [InverseProperty("Schedule")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("RegistrationId")]
    [InverseProperty("WorkSchedules")]
    public virtual Registration Registration { get; set; }

    [ForeignKey("RoomId")]
    [InverseProperty("WorkSchedules")]
    public virtual Room Room { get; set; }
}